window.DataSeed = {
    getData() {
        const rawCards = [
            { card_id: 1, primary_cardholder: 'Alok Harlalka', card_category: 'Primary', cardholder_name: 'Alok Harlalka', zoho_ledger_name: 'Alok ICICI Credit Card', card_type: 'ICICI Emerald Visa', card_number: '4611330107440004', address: '3H VERONICA 6B,DHAPA,ACTIVE ACRES,TANGRA , KOLKATA, WEST BENGAL, 700015', email: 'billing@gretexgroup.com', phone: '9830088638' },
            { card_id: 2, primary_cardholder: 'Alok Harlalka', card_category: 'Add-on', cardholder_name: 'YASH HARLALKA', zoho_ledger_name: 'Alok ICICI Credit Card', card_type: 'ICICI Emerald Visa', card_number: '4611330107443891', address: '3H VERONICA 6B,DHAPA,ACTIVE ACRES,TANGRA , KOLKATA, WEST BENGAL, 700015', email: 'billing@gretexgroup.com', phone: '9830088638' },
            { card_id: 3, primary_cardholder: 'Alok Harlalka', card_category: 'Add-on', cardholder_name: 'TANISHKA HARLALKA', zoho_ledger_name: 'Alok ICICI Credit Card', card_type: 'ICICI Emerald Visa', card_number: '4611330107443909', address: '3H VERONICA 6B,DHAPA,ACTIVE ACRES,TANGRA , KOLKATA, WEST BENGAL, 700015', email: 'billing@gretexgroup.com', phone: '9830088638' },
            { card_id: 4, primary_cardholder: 'Alok Harlalka', card_category: 'Primary', cardholder_name: 'Alok Harlalka', zoho_ledger_name: 'Alok HDFC Credit Card', card_type: 'HDFC Infinia Metal', card_number: '5399830105050397', address: 'FLAT NO.3H/BL-6/ACTIVE ACRES, VERONICA,D.C. DEY ROAD, DHAPA KOLKATA KOLKATA, WEST BENGAL - 700015', email: 'billing@gretexgroup.com', phone: '9830088638' },
            { card_id: 5, primary_cardholder: 'Alok Harlalka', card_category: 'Add-on', cardholder_name: 'YASH HARLALKA', zoho_ledger_name: 'Alok HDFC Credit Card', card_type: 'HDFC Infinia Metal', card_number: '5399830102063493', address: 'FLAT NO.3H/BL-6/ACTIVE ACRES, VERONICA,D.C. DEY ROAD, DHAPA KOLKATA KOLKATA, WEST BENGAL - 700015', email: 'billing@gretexgroup.com', phone: '9830088638' },
            { card_id: 6, primary_cardholder: 'Alok Harlalka', card_category: 'Add-on', cardholder_name: 'TANISHKA HARLALKA', zoho_ledger_name: 'Alok HDFC Credit Card', card_type: 'HDFC Infinia Metal', card_number: '5399830102064301', address: 'FLAT NO.3H/BL-6/ACTIVE ACRES, VERONICA,D.C. DEY ROAD, DHAPA KOLKATA KOLKATA, WEST BENGAL - 700015', email: 'billing@gretexgroup.com', phone: '9830088638' },
            { card_id: 7, primary_cardholder: 'Alok Harlalka', card_category: 'Add-on', cardholder_name: 'Pooja Harlalka', zoho_ledger_name: 'Alok HDFC Credit Card', card_type: 'HDFC Infinia Metal', card_number: '5399830102065001', address: 'FLAT NO.3H/BL-6/ACTIVE ACRES, VERONICA,D.C. DEY ROAD, DHAPA KOLKATA KOLKATA, WEST BENGAL - 700015', email: 'billing@gretexgroup.com', phone: '9830088638' },
            { card_id: 8, primary_cardholder: 'Alok Harlalka', card_category: 'Add-on', cardholder_name: 'Rajkumari Harlalka', zoho_ledger_name: 'Alok HDFC Credit Card', card_type: 'HDFC Infinia Metal', card_number: '5399 83xx xx48 95', address: 'FLAT NO.3H/BL-6/ACTIVE ACRES, VERONICA,D.C. DEY ROAD, DHAPA KOLKATA KOLKATA, WEST BENGAL - 700015', email: 'billing@gretexgroup.com', phone: '9830088638' },
            { card_id: 9, primary_cardholder: 'Alok Harlalka', card_category: 'Primary', cardholder_name: 'Alok Harlalka', zoho_ledger_name: 'Alok SBI Credit Card', card_type: 'SBI Aurum', card_number: '4768730000029003', address: '3H/BL-6,ACTIVE ACRES,VERONICA TOWER,D.C.DEY ROAD, KOLKATA 700015', email: 'billing@gretexgroup.com', phone: '9830088638' },
            { card_id: 10, primary_cardholder: 'Alok Harlalka', card_category: 'Add-on', cardholder_name: 'Pooja Harlalka', zoho_ledger_name: 'Alok SBI Credit Card', card_type: 'SBI Aurum', card_number: '4768730000029011', address: '3H/BL-6,ACTIVE ACRES,VERONICA TOWER,D.C.DEY ROAD, KOLKATA 700015', email: 'billing@gretexgroup.com', phone: '9830088638' },
            { card_id: 11, primary_cardholder: 'Gourav Harlalka', card_category: 'Primary', cardholder_name: 'Gourav Harlalka', zoho_ledger_name: 'Gourav ICICI CC', card_type: 'ICICI Sapphiro', card_number: '4611330107461984', address: 'FLAT NO 3E BL 6 ACTIVE ACRS VERO,NICA TWR DC DEY ROAD DHAPA, KOLKATA, WEST BENGAL - 700015', email: 'billing@gretexgroup.com', phone: '9830525765' },
            { card_id: 12, primary_cardholder: 'Gourav Harlalka', card_category: 'Add-on', cardholder_name: 'Arvind Harlalka', zoho_ledger_name: 'Gourav ICICI CC', card_type: 'ICICI Sapphiro', card_number: '4611330107461992', address: 'FLAT NO 3E BL 6 ACTIVE ACRS VERO,NICA TWR DC DEY ROAD DHAPA, KOLKATA, WEST BENGAL - 700015', email: 'billing@gretexgroup.com', phone: '9830025765' },
            { card_id: 13, primary_cardholder: 'Gourav Harlalka', card_category: 'Primary', cardholder_name: 'Gourav Harlalka', zoho_ledger_name: 'Gourav HDFC CC', card_type: 'HDFC Infinia Metal', card_number: '5399830109088192', address: '54/10 BL-6 FL-3E ACTIVE ACRES, TANGRA KOLKATA - 700015', email: 'billing@gretexgroup.com', phone: '9830525765' },
            { card_id: 14, primary_cardholder: 'Gourav Harlalka', card_category: 'Add-on', cardholder_name: 'Arvind Harlalka', zoho_ledger_name: 'Gourav HDFC CC', card_type: 'HDFC Infinia Metal', card_number: '5399830108090686', address: '54/10 BL-6 FL-3E ACTIVE ACRES, TANGRA KOLKATA - 700015', email: 'billing@gretexgroup.com', phone: '9830025765' },
            { card_id: 15, primary_cardholder: 'Gourav Harlalka', card_category: 'Add-on', cardholder_name: 'Alok Harlalka', zoho_ledger_name: 'Gourav HDFC CC', card_type: 'HDFC Infinia Metal', card_number: '5399830108088219', address: '54/10 BL-6 FL-3E ACTIVE ACRES, TANGRA KOLKATA - 700015', email: 'billing@gretexgroup.com', phone: '9830088638' },
            { card_id: 16, primary_cardholder: 'Gourav Harlalka', card_category: 'Add-on', cardholder_name: 'Harsh Harlalka', zoho_ledger_name: 'Gourav HDFC CC', card_type: 'HDFC Infinia Metal', card_number: '5399830108087831', address: '54/10 BL-6 FL-3E ACTIVE ACRES, TANGRA KOLKATA - 700015', email: 'billing@gretexgroup.com', phone: '9830525765' },
            { card_id: 17, primary_cardholder: 'Arvind Harlalka', card_category: 'Primary', cardholder_name: 'Arvind Harlalka', zoho_ledger_name: 'Arvind HDFC CC', card_type: 'HDFC Diners Black Metal', card_number: '36088613577652', address: 'ACTIVE ACRES VERONICA TOWER, FLAT NO 3E TOWER NO 6B 54/10 BC, DEY ROAD DHAPA, KOLKATA, WEST BENGAL - 700***, INDIA', email: 'billing@gretexgroup.com', phone: '9830025765' },
            { card_id: 18, primary_cardholder: 'Arvind Harlalka', card_category: 'Add-on', cardholder_name: 'Harsh Harlalka', zoho_ledger_name: 'Arvind HDFC CC', card_type: 'HDFC Diners Black Metal', card_number: '36088613584930', address: 'ACTIVE ACRES VERONICA TOWER, FLAT NO 3E TOWER NO 6B 54/10 BC, DEY ROAD DHAPA, KOLKATA, WEST BENGAL - 700***, INDIA', email: 'billing@gretexgroup.com', phone: '9830525765' },
            { card_id: 19, primary_cardholder: 'Arvind Harlalka', card_category: 'Add-on', cardholder_name: 'Anita Harlalka', zoho_ledger_name: 'Arvind HDFC CC', card_type: 'HDFC Diners Black Metal', card_number: '36088613587297', address: 'ACTIVE ACRES VERONICA TOWER, FLAT NO 3E TOWER NO 6B 54/10 BC, DEY ROAD DHAPA, KOLKATA, WEST BENGAL - 700***, INDIA', email: 'billing@gretexgroup.com', phone: '9830525765' },
            { card_id: 20, primary_cardholder: 'Arvind Harlalka', card_category: 'Add-on', cardholder_name: 'Rajkumari Harlalka', zoho_ledger_name: 'Arvind HDFC CC', card_type: 'HDFC Diners Black Metal', card_number: '3608 86xx xx38 73', address: 'ACTIVE ACRES VERONICA TOWER, FLAT NO 3E TOWER NO 6B 54/10 BC, DEY ROAD DHAPA, KOLKATA, WEST BENGAL - 700***, INDIA', email: 'billing@gretexgroup.com', phone: '9830525765' },
            { card_id: 21, primary_cardholder: 'Arvind Harlalka', card_category: 'Add-on', cardholder_name: 'Gourav Harlalka', zoho_ledger_name: 'Arvind HDFC CC', card_type: 'HDFC Diners Black Metal', card_number: '36088613601908', address: 'ACTIVE ACRES VERONICA TOWER, FLAT NO 3E TOWER NO 6B 54/10 BC, DEY ROAD DHAPA, KOLKATA, WEST BENGAL - 700***, INDIA', email: 'billing@gretexgroup.com', phone: '9830525765' },
            { card_id: 22, primary_cardholder: 'Gourav Harlalka', card_category: 'Primary', cardholder_name: 'Gourav Harlalka', zoho_ledger_name: 'Gourav HDFC Swiggy CC', card_type: 'Swiggy HDFC Bank Credit Card', card_number: '5268730001830783', address: '54/10 BL 6 FL 3E TANGRA, KOLKATA, WEST BENGAL - 700***, INDIA', email: 'billing@gretexgroup.com', phone: '9830525765' },
            { card_id: 23, primary_cardholder: 'Gourav Harlalka', card_category: 'Primary', cardholder_name: 'Gourav Harlalka', zoho_ledger_name: 'HSBC', card_type: 'HSBC Travel One Credit Card', card_number: '5177827301480606', address: '54 10 BL 6 FL 3E, TANGRA 19   KOLKATA- 700015 INDIA 700015', email: 'gourav@gretexgroup.com', phone: '9830525765' },
            { card_id: 24, primary_cardholder: 'Alok Harlalka', card_category: 'Primary', cardholder_name: 'Alok Harlalka', zoho_ledger_name: 'Alok Axis CC', card_type: 'Axis Vistara Infinite', card_number: '4308340000645086', address: '54/10 D.C. DEY ROAD, ACTIVE ACRES, TOWER 6B, FLAT- 3E KOLKATA, KOLKATA - 700015', email: 'alok@gretexgroup.com', phone: '9830088638' },
            { card_id: 25, primary_cardholder: 'Arvind Harlalka', card_category: 'Primary', cardholder_name: 'Arvind Harlalka', zoho_ledger_name: 'Arvind Axis CC', card_type: 'Axis Magnus Burgundy', card_number: '5296290500198873', address: '54/10 FL 3E DEBENDRA CHANDRA DEY, ROAD DHAPA TANGRA KOLKATA WEST BENGAL J W MARRITTO, Kolkata 70015', email: 'arvind@gretexgroup.com', phone: '9830025765' },
            { card_id: 26, primary_cardholder: 'Arvind Harlalka', card_category: 'Add-on', cardholder_name: 'Harsh Harlalka', zoho_ledger_name: 'Arvind Axis CC', card_type: 'Axis Magnus Burgundy', card_number: '5296290500219810', address: '54/10 FL 3E DEBENDRA CHANDRA DEY, ROAD DHAPA TANGRA KOLKATA WEST BENGAL J W MARRITTO, Kolkata 70015', email: 'arvind@gretexgroup.com', phone: '9830025765' },
            { card_id: 27, primary_cardholder: 'Arvind Harlalka', card_category: 'Add-on', cardholder_name: 'Gourav Harlalka', zoho_ledger_name: 'Arvind Axis CC', card_type: 'Axis Magnus Burgundy', card_number: '5296290500223531', address: '54/10 FL 3E DEBENDRA CHANDRA DEY, ROAD DHAPA TANGRA KOLKATA WEST BENGAL J W MARRITTO, Kolkata 70015', email: 'arvind@gretexgroup.com', phone: '9830525765' },
            { card_id: 28, primary_cardholder: 'Arvind Harlalka', card_category: 'Add-on', cardholder_name: 'Anita Harlalka', zoho_ledger_name: 'Arvind Axis CC', card_type: 'Axis Magnus Burgundy', card_number: '5296290500262710', address: '54/10 FL 3E DEBENDRA CHANDRA DEY, ROAD DHAPA TANGRA KOLKATA WEST BENGAL J W MARRITTO, Kolkata 70015', email: 'arvind@gretexgroup.com', phone: '9330730021' },
            { card_id: 29, primary_cardholder: 'Arvind Harlalka', card_category: 'Add-on', cardholder_name: 'Rajkumari Harlalka', zoho_ledger_name: 'Arvind Axis CC', card_type: 'Axis Magnus Burgundy', card_number: '5296 xxxx xxxx 7242', address: '54/10 FL 3E DEBENDRA CHANDRA DEY, ROAD DHAPA TANGRA KOLKATA WEST BENGAL J W MARRITTO, Kolkata 70015', email: 'arvind@gretexgroup.com', phone: '9331230792' },
            { card_id: 30, primary_cardholder: 'Gourav Harlalka', card_category: 'Primary', cardholder_name: 'Gourav Harlalka', zoho_ledger_name: 'Gourav Axis cc 3650', card_type: 'Axis Vistara Infinite', card_number: '5334670000000000', address: 'S/O: ARVIND HARLALKA,54/10 BL-6 FL-3E, TANGRA, TANGRA, KOLKATA, KOLKATA- 700015', email: 'gaurav232001@gmail.com', phone: '9830525765' },
            { card_id: 31, primary_cardholder: 'Alok Harlalka', card_category: 'Primary', cardholder_name: 'Alok Harlalka', zoho_ledger_name: 'Alok Amex CC 1009', card_type: 'Amex Platinum Travel Credit Card', card_number: '373007431021009', address: '3H ACTIVE ACRES VERONICA 6B', email: 'alok@gretexgroup.com', phone: '9830088638' },
            { card_id: 32, primary_cardholder: 'Alok Harlalka', card_category: 'Add-on', cardholder_name: 'YASH HARLALKA', zoho_ledger_name: 'Alok Amex CC 1009', card_type: 'Amex Platinum Travel Credit Card', card_number: '373007431021017', address: '3H ACTIVE ACRES VERONICA 6B', email: 'alok@gretexgroup.com', phone: '9830088638' },
            { card_id: 33, primary_cardholder: 'Alok Harlalka', card_category: 'Add-on', cardholder_name: 'TANISHKA HARLALKA', zoho_ledger_name: 'Alok Amex CC 1009', card_type: 'Amex Platinum Travel Credit Card', card_number: '(empty)', address: '3H ACTIVE ACRES VERONICA 6B', email: 'alok@gretexgroup.com', phone: '9830088638' },
            { card_id: 34, primary_cardholder: 'Arvind Harlalka', card_category: 'Primary', cardholder_name: 'Arvind Harlalka', zoho_ledger_name: 'Arvind Amex 61007 CC', card_type: 'Amex Platinum Travel Credit Card', card_number: '379871707461007', address: '54/10, FI 3E DEBENDRA CHANDRA DEY ROAD DHAPA TANGRA', email: 'arvind@gretexgroup.com', phone: '9830025765' },
            { card_id: 35, primary_cardholder: 'Arvind Harlalka', card_category: 'Add-on', cardholder_name: 'Harsh Harlalka', zoho_ledger_name: 'Arvind Amex 61007 CC', card_type: 'Amex Platinum Travel Credit Card', card_number: '376936528921068', address: '54/10, FI 3E DEBENDRA CHANDRA DEY ROAD DHAPA TANGRA', email: 'arvind@gretexgroup.com', phone: '9830025765' },
            { card_id: 36, primary_cardholder: 'Arvind Harlalka', card_category: 'Add-on', cardholder_name: 'Rajkumari Harlalka', zoho_ledger_name: 'Arvind Amex 61007 CC', card_type: 'Amex Platinum Travel Credit Card', card_number: '1379 8717 0746 1023', address: '54/10, FI 3E DEBENDRA CHANDRA DEY ROAD DHAPA TANGRA', email: 'arvind@gretexgroup.com', phone: '9830025765' },
            { card_id: 37, primary_cardholder: 'Arvind Harlalka', card_category: 'Primary', cardholder_name: 'Arvind Harlalka', zoho_ledger_name: 'Arvind Amex Credit Card 22009', card_type: 'Amex Platinum Reserve Credit Card', card_number: '376936528922009', address: '54/10, FI 3E DEBENDRA CHANDRA DEY ROAD DHAPA TANGRA', email: 'arvind@gretexgroup.com', phone: '9830025765' },
            { card_id: 38, primary_cardholder: 'Arvind Harlalka', card_category: 'Add-on', cardholder_name: 'Alok Harlalka', zoho_ledger_name: 'Arvind Amex Credit Card 22009', card_type: 'Amex Platinum Reserve Credit Card', card_number: '376836528921019', address: '54/10, FI 3E DEBENDRA CHANDRA DEY ROAD DHAPA TANGRA', email: 'arvind@gretexgroup.com', phone: '9830025765' },
            { card_id: 39, primary_cardholder: 'Arvind Harlalka', card_category: 'Add-on', cardholder_name: 'Pooja Harlalka', zoho_ledger_name: 'Arvind Amex Credit Card 22009', card_type: 'Amex Platinum Reserve Credit Card', card_number: '376936528921027', address: '54/10, FI 3E DEBENDRA CHANDRA DEY ROAD DHAPA TANGRA', email: 'arvind@gretexgroup.com', phone: '9830025765' },
            { card_id: 40, primary_cardholder: 'Arvind Harlalka', card_category: 'Add-on', cardholder_name: 'Rajkumari Harlalka', zoho_ledger_name: 'Arvind Amex Credit Card 22009', card_type: 'Amex Platinum Reserve Credit Card', card_number: '1379 8717 0746 1023', address: '54/10, FI 3E DEBENDRA CHANDRA DEY ROAD DHAPA TANGRA', email: 'arvind@gretexgroup.com', phone: '9830025765' },
            { card_id: 41, primary_cardholder: 'Arvind Harlalka', card_category: 'Add-on', cardholder_name: 'Anita Harlalka', zoho_ledger_name: 'Arvind Amex Credit Card 22009', card_type: 'Amex Platinum Reserve Credit Card', card_number: '374741727627009', address: '54/10, FI 3E DEBENDRA CHANDRA DEY ROAD DHAPA TANGRA', email: 'arvind@gretexgroup.com', phone: '9830025765' },
            { card_id: 42, primary_cardholder: 'Arvind Harlalka', card_category: 'Add-on', cardholder_name: 'Gourav Harlalka', zoho_ledger_name: 'Arvind Amex Credit Card 22009', card_type: 'Amex Platinum Reserve Credit Card', card_number: '374741683810003', address: '54/10, FI 3E DEBENDRA CHANDRA DEY ROAD DHAPA TANGRA', email: 'arvind@gretexgroup.com', phone: '9830025765' },
            { card_id: 43, primary_cardholder: 'Arvind Harlalka', card_category: 'Add-on', cardholder_name: 'Harsh Harlalka', zoho_ledger_name: 'Arvind Amex Credit Card 22009', card_type: 'Amex Platinum Reserve Credit Card', card_number: '1379871707461010', address: '54/10, FI 3E DEBENDRA CHANDRA DEY ROAD DHAPA TANGRA', email: 'arvind@gretexgroup.com', phone: '9830025765' },
            { card_id: 44, primary_cardholder: 'Arvind Harlalka', card_category: 'Primary', cardholder_name: 'Arvind IDFC Credit Card', zoho_ledger_name: 'Arvind IDFC Credit Card', card_type: 'IDFC First Credit Card', card_number: '4281021018416881', address: 'C/O,,54/10, Fl-3e,Debendra Chandra Dey Road,Dhapa,Tangra . Kolkata Kolkata - 700015 WEST BENGAL INDIA', email: 'arvind@gretexgroup.com', phone: '9830025765' }
        ];

        const credit_cards = rawCards.map(c => {
            const now = new Date().toISOString();
            return {
                ...c,
                bank_name: window.Utils ? window.Utils.extractBankName(c.card_type) : '',
                card_last4: window.Utils ? window.Utils.getLast4(c.card_number) : '',
                credit_limit: 0,
                statement_date: 0,
                due_date: 0,
                renewal_date: '',
                fee_waiver_target: 0,
                reward_points: 0,
                status: 'Active',
                remarks: '',
                created_at: now,
                updated_at: now
            };
        });

        const categories = [
            { category_id: 1, category_name: 'Travel', description: 'Flight, hotel, cab bookings' },
            { category_id: 2, category_name: 'Food & Dining', description: 'Restaurants, food delivery, groceries' },
            { category_id: 3, category_name: 'Shopping', description: 'Online and offline retail purchases' },
            { category_id: 4, category_name: 'Fuel', description: 'Petrol, diesel, EV charging' },
            { category_id: 5, category_name: 'Entertainment', description: 'Movies, OTT subscriptions, events' },
            { category_id: 6, category_name: 'Utilities', description: 'Electricity, water, internet, phone bills' },
            { category_id: 7, category_name: 'Insurance', description: 'Life, health, vehicle insurance premiums' },
            { category_id: 8, category_name: 'Medical', description: 'Hospital, pharmacy, diagnostic expenses' },
            { category_id: 9, category_name: 'Business', description: 'Office supplies, services, professional expenses' },
            { category_id: 10, category_name: 'Uncategorized', description: 'Unclassified transactions' }
        ];

        return {
            credit_cards: credit_cards,
            transactions: [],
            statements: [],
            payments: [],
            categories: categories,
            import_batches: []
        };
    }
};
